name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.RPI_SSH_KEY }}

    - name: Copy code to Raspberry Pi
      run: |
        scp counter.cpp adity@192.168.0.103:/home/adity/projects/counter_project/counter.cpp

    - name: Build and run on Raspberry Pi
      run: |
        ssh adity@192.168.0.103 << 'EOF'
        g++ /home/adity/projects/counter_project/counter.cpp -o /home/adity/projects/counter_project/counter
        /home/adity/projects/counter_project/counter
        EOF

    - name: Trigger pull and run script
      run: |
        ssh adity@192.168.0.103 "bash /home/adity/projects/counter_project/pull_and_run.sh"
