name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.RPI_SSH_KEY }}

    - name: Copy code to Raspberry Pi
      run: |
        scp led_blink.cpp adity@192.168.0.103:/home/adity/led_blink.cpp

    - name: Build and run on Raspberry Pi
      run: |
        ssh adity@192.168.0.103 << EOF
        g++ /home/adity/led_blink.cpp -o /home/adity/led_blink
        sudo /home/adity/led_blink
        EOF
