name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.6.0
      with:
        ssh-private-key: ${{ secrets.RPI_SSH_KEY }}

    - name: Copy code to Raspberry Pi
      run: |
        scp -o StrictHostKeyChecking=no -P 11859 counter.cpp adity@2.tcp.us-cal-1.ngrok.io:/home/adity/projects/counter_project/counter.cpp

    - name: Build and run on Raspberry Pi
      run: |
        ssh -o StrictHostKeyChecking=no adity@2.tcp.us-cal-1.ngrok.io -p 11859 "g++ /home/adity/projects/counter_project/counter.cpp -o /home/adity/projects/counter_project/counter && DISPLAY=:0 lxterminal -e '/home/adity/projects/counter_project/counter'"
